encoding: UTF-8

header_pages:
        - about
        - tech
        - cyber
        - poi
        - book
        - sound
        - other

collections:
     artist:
       output: true
       sort_by: 'nickname'
     group:
       output: true
       sort_by: 'name'
     video:
       output: true
       sort_by: 'name'

collections_dir: 'PTL'

defaults:
  - scope:
      path: ""
      type: "artist"
    values:
      layout: "artist"
  - scope:
      path: ""
      type: "group"
    values:
      layout: "group"
  - scope:
      path: ""
      type: "video"
    values:
      layout: "video"
  - scope:
      path: ""
    values:
      layout: "default"

footer: '&#960;'

